# Generated by Django 5.0.6 on 2024-06-10 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thruster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('motor_efficiency', models.JSONField()),
                ('motor_load', models.JSONField()),
                ('P_D', models.JSONField()),
                ('transist_j', models.JSONField()),
                ('transist_kt_tot', models.JSONField()),
                ('transist_kq10', models.JSONField()),
                ('propeller_rpm_1min', models.JSONField()),
                ('propeller_power_kw', models.JSONField()),
                ('thruster_efficiency_40c', models.JSONField()),
                ('max_rpm', models.FloatField()),
                ('max_power', models.DecimalField(decimal_places=2, max_digits=10)),
                ('propeller_diameter', models.DecimalField(decimal_places=2, max_digits=10)),
                ('wake_factor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('thrust_deduction', models.DecimalField(decimal_places=2, max_digits=10)),
                ('relative_rotative_efficiency', models.DecimalField(decimal_places=2, max_digits=10)),
                ('auxiliary_consumption_kW', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
