# Generated by Django 5.0.6 on 2024-06-10 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thruster',
            name='auxiliary_consumption_kW',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='thruster',
            name='max_power',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='thruster',
            name='max_rpm',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='thruster',
            name='propeller_diameter',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='thruster',
            name='relative_rotative_efficiency',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='thruster',
            name='thrust_deduction',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='thruster',
            name='wake_factor',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
