# Generated by Django 5.0.6 on 2024-06-10 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opex', '0002_alter_thruster_auxiliary_consumption_kw_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thruster',
            name='P_D',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='thruster',
            name='auxiliary_consumption_kW',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='thruster',
            name='max_power',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='thruster',
            name='max_rpm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='thruster',
            name='motor_efficiency',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='thruster',
            name='motor_load',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='thruster',
            name='propeller_diameter',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='thruster',
            name='propeller_power_kw',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='thruster',
            name='propeller_rpm_1min',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='thruster',
            name='relative_rotative_efficiency',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='thruster',
            name='thrust_deduction',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='thruster',
            name='thruster_efficiency_40c',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='thruster',
            name='transist_j',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='thruster',
            name='transist_kq10',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='thruster',
            name='transist_kt_tot',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='thruster',
            name='wake_factor',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
