# Generated by Django 5.0.6 on 2024-06-11 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opex', '0004_vessel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thruster',
            name='P_D',
            field=models.JSONField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='thruster',
            name='motor_efficiency',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='thruster',
            name='motor_load',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='thruster',
            name='propeller_power_kw',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='thruster',
            name='propeller_rpm_1min',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='thruster',
            name='thruster_efficiency_40c',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='thruster',
            name='transist_j',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='thruster',
            name='transist_kq10',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='thruster',
            name='transist_kt_tot',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='hours',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='stw_knots',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='thrust_kn',
            field=models.JSONField(),
        ),
    ]
