# Generated by Django 5.0.6 on 2024-06-11 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opex', '0005_alter_thruster_p_d_alter_thruster_motor_efficiency_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vessel',
            old_name='thrust_kn',
            new_name='thrust_kN',
        ),
    ]
