# Generated by Django 5.0.6 on 2024-06-11 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opex', '0006_rename_thrust_kn_vessel_thrust_kn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thruster',
            old_name='propeller_power_kw',
            new_name='propeller_power_kW',
        ),
        migrations.RenameField(
            model_name='thruster',
            old_name='thruster_efficiency_40c',
            new_name='thruster_efficiency_40C',
        ),
    ]
