# Generated by Django 5.0.6 on 2024-06-11 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opex', '0007_rename_propeller_power_kw_thruster_propeller_power_kw_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thruster',
            name='auxiliary_consumption_kW',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='thruster',
            name='max_power',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='thruster',
            name='max_rpm',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='thruster',
            name='propeller_diameter',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='thruster',
            name='relative_rotative_efficiency',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='thruster',
            name='thrust_deduction',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='thruster',
            name='wake_factor',
            field=models.FloatField(),
        ),
    ]
