name: Organization Workflow Base

on:
  pull_request:

jobs:
  coverage:
    uses: Kongsberg-Predictive-Maintenance/actions/.github/workflows/coverage-configuration.yml@development
    secrets:
      organization_key: ${{ secrets.MACHINE_USER_PRIVATE_KEY }}